"use strict";
const bcrypt = require("bcrypt");
const { SALT_ROUNDS } = require("../config/constants");

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("users", [
      {
        email: "john@john.com",
        password: bcrypt.hashSync("john", SALT_ROUNDS),
        firstName: "John",
        lastName: "Smith",
        address: "Herentalsstraat 93, 1066NL Amsterdam",
        phoneNum: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        isOwner: true,
      },
      {
        email: "sam@sam.com",
        password: bcrypt.hashSync("sam", SALT_ROUNDS),
        firstName: "Sam",
        lastName: "Jones",
        address: "Radarweg 224, 1043NS Amsterdam",
        phoneNum: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        isOwner: false,
      },
      {
        email: "michael@michael.com",
        password: bcrypt.hashSync("michael", SALT_ROUNDS),
        firstName: "Michael",
        lastName: "Norton",
        address: "Slotevaart 14, 1065TD Amsterdam",
        phoneNum: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        isOwner: false,
      },
      {
        email: "andrew@andrew.com",
        password: bcrypt.hashSync("andrew", SALT_ROUNDS),
        firstName: "Andrew",
        lastName: "Richardsson",
        address: "Van Eeghenstraat 103, 1071GM Amsterdam",
        phoneNum: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        isOwner: false,
      },
      {
        email: "frank@frank.com",
        password: bcrypt.hashSync("frank", SALT_ROUNDS),
        firstName: "Frank",
        lastName: "Carpaccio",
        address: "Tweede Oosterparkstraat 254, 1092BS Amsterdam",
        phoneNum: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        isOwner: true,
      },
      {
        email: "carl@carl.com",
        password: bcrypt.hashSync("carl", SALT_ROUNDS),
        firstName: "Carl",
        lastName: "Powe",
        address: "Valeriusstraat 46, 1071MN Amsterdam",
        phoneNum: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        isOwner: false,
      },
      {
        email: "tim@tim.com",
        password: bcrypt.hashSync("tim", SALT_ROUNDS),
        firstName: "Tim",
        lastName: "Donelly",
        address: "Kuipersstraat 156, 1073TJ Amsterdam",
        phoneNum: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        isOwner: true,
      },
      {
        email: "robert@robert.com",
        password: bcrypt.hashSync("robert", SALT_ROUNDS),
        firstName: "Robert",
        lastName: "Desimone",
        address: "Van Ostadestraat 62, 1072SX Amsterdam",
        phoneNum: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        isOwner: false,
      },
      {
        email: "luis@luis.com",
        password: bcrypt.hashSync("luis", SALT_ROUNDS),
        firstName: "Luis",
        lastName: "Crist",
        address: "Spuistraat 211, 1012VT Amsterdam",
        phoneNum: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        isOwner: false,
      },
      {
        email: "kenny@kenny.com",
        password: bcrypt.hashSync("kenny", SALT_ROUNDS),
        firstName: "Kenny",
        lastName: "Wilson",
        address: "Nieuwe Herengracht 111, 1011SG Amsterdam",
        phoneNum: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        isOwner: false,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("users", null, {});
  },
};
